### ISSUE TITLE
API returns empty result

### ISSUE THREAD

**Issue by luciekaffee** [debayan/pnel#5]
The live API returns no entities for the example request

`$ curl -XPOST 'ltdemos.informatik.uni-hamburg.de/pnel/processQuery' -H 'Content-Type: application/json' \
-d"{\"nlquery\":\"is joe biden the president or is donald trump ?\"}"`

I.e., the result of this request is

`{
    "entities": {},
    "nlquery": "is joe biden the president or is donald trump ?"
}%   `

**Comment by debayan** [comment]
Hi Lucie,

Sorry or the delay, I was on vacation. It works now.
